siemens_pdf = '../../1_Reports/Sample_Reports/Siemens Energy-sustainability-report-2020.pdf'
allianz_pdf = '../../1_Reports/Sample_Reports/Allianz_Group_Sustainability_Report_2020-web.pdf'
siemens_page_23 = '../../1_Reports/Sample_Reports/SiemensPage23.pdf'
siemens_page_27 = '../../1_Reports/Sample_Reports/SiemensPage27.pdf'
allianz_page_106 = '../../1_Reports/Sample_Reports/Allianz_Group_Sustainability_Report_2020-web-page-106.pdf'
acroform = '../../1_Reports/Sample_Reports/AcroForm_TEST.pdf'
